# Lista de exercícios sobre libraria Numpy

<br/>**Disciplina**: Introdução a redes neurais profundas 2018/2
<br/>**Professor**: Jorge Leonid Aching Samatelo

**Aluno**: Pedro Farias

## Tabela de conteúdos
1. [Indicações](#indicacoes)
1. [Exercícios sobre Numpy](#ExerNumpy)
1. [Exercícios de Programação](#ExerProgramacao)
1. [Exercícios de Vetorização](#ExerVetor)

## Indicações <a name="indicacoes"></a>

### Considerações
* Cada aluno enviará por e-mail a solução dos exercícios propostos, tais soluções devem ser inseridas neste mesmo arquivo. 
* Para saber sobre a libraria `numpy` é necessario ler os slides `NUMPY_2x2.pdf`.
* Para saber cómo trabalhar com arquivos `*.ipynb` é necessario ler os slides `003_JUPYTER_2x2.pdf`.
* Usar o interprete de `python 3.5`.

### Prazo
* Envio das soluções: 30/08/2018 - (23:59 hrs) 

### Procedimento para o envio das soluções
* O arquivo `*.ipynb` com as soluções dos exercícios deve ser enviado ao email <jlasam001@gmail.com> com o assunto: `LISTA_EXERCICIO_NUMPY_2018_2`. 
* O nome do arquivo `*.ipynb` deve iniciar com o rotulo `DL_LISTA_NUMPY` seguido pelas iniciais do nome do aluno que soluciono os exercícios (por exemplo, o aluno Pedro Farias enviara o arquivo `DL_LISTA_NUMPY_PF.ipynb`).

### Dicas execução
* Carregue todos os pacotes que serão necessários no início do arquivo.
* Para executar comandos da shell dentro do notebook, utilize o prefixo `!` antes do comando de shell. (e.g. para listar os arquivos da pasta atual faça `! ls` para UNIX ou `! dir` para Windows.

## Exercícios sobre Numpy <a name="ExerString"></a>

### Exe. 1
Crie uma matriz nxn com valores 1,2,...,n-1 logo abaixo da diagonal.

Exemplo: Considerando n = 4.
```
A = [0 0 0 0 0]
    [1 0 0 0 0]
    [0 2 0 0 0]
    [0 0 3 0 0]
    [0 0 0 4 0]
```

In [11]:
import numpy as np
n = 4

A = np.zeros((n+1,n+1))
A[1:,:-1] = np.diag(np.arange(1,n+1))
print(A)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


### Exe. 2
Crie uma matriz nxn com 1 na borda e 0 dentro.

Exemplo: Considerando n = 10.
```
Z = [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
```

In [13]:
import numpy as np
n = 10

Z = np.ones((n,n))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Exe. 3
Crie uma matriz nxn, com n par, e preenchê-lo com um padrão de xadrez.

Exemplo: Considerando n = 8.
```
Z = [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
```

In [23]:
import numpy as np
n = 8

Z = np.ones((n,n))
Z[::2,::2] = 0
Z[1::2,1::2] = 0
print(Z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### Exe. 4
Criar um vetor de tamanho 10 inicializada com valores entre $<0,1>$.

Exemplo:
```
Z= [0.091 0.181 0.272 0.363 0.454 0.545 0.636 0.727 0.818 0.909]
```

In [29]:
import numpy as np
n = 10

Z = np.linspace(0,1,n+2).round(3)[1:-1]
print(Z)

[0.091 0.182 0.273 0.364 0.455 0.545 0.636 0.727 0.818 0.909]


### Exe. 5
Dado um array, negar todos os elementos que estão entre 3 e 8.

Exemplo:
```
Zorg =  [ 0  1  2  3  4  5  6  7  8  9 10]
Ztrf =  [ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
```

In [32]:
import numpy as np
n = 10
a = 3
b = 8

Zorg = np.arange(0, n+1)
o = np.ones(n+1)
o[np.logical_and(Zorg > a, Zorg <= b)] = -1
Ztrf = Zorg*o

print('Zorg =', Zorg)
print('Ztrf =', Ztrf)

Zorg = [ 0  1  2  3  4  5  6  7  8  9 10]
Ztrf = [ 0.  1.  2.  3. -4. -5. -6. -7. -8.  9. 10.]


### Exe. 6
Extraia a parte inteira de uma array de números aleatórios entre  1.0 e 10.0 usando 5 métodos diferentes.

Exemplo (para um caso):
```
Z  =  [7.497 6.573 9.946 2.645 2.501 8.911 4.301 9.643 4.361 4.128]
Z1 =  [ 7.  6.  9.  2.  2.  8.  4.  9.  4.  4.]
```

In [5]:
import numpy as np
import math

Z = np.array([7.497, 6.573, 9.946, 2.645, 2.501, 8.911, 4.301, 9.643, 4.361, 4.128])

print('map + int:', list(map(int,Z)))
print('map + math.floor:', list(map(math.floor,Z)))
print('int division:', Z//1)
print('real subtraction:', Z - Z%1)
print('np.floor:', np.floor(Z))

map + int: [7, 6, 9, 2, 2, 8, 4, 9, 4, 4]
map + math.floor: [7, 6, 9, 2, 2, 8, 4, 9, 4, 4]
int division: [7. 6. 9. 2. 2. 8. 4. 9. 4. 4.]
real subtraction: [7. 6. 9. 2. 2. 8. 4. 9. 4. 4.]
np.floor: [7. 6. 9. 2. 2. 8. 4. 9. 4. 4.]


### Exe. 7
Considere dois arrays $A$ e $B$ aleatórios inicializados com valores aleatorios inteiros, verifique se eles são iguais.

Exemplo:
```
A =  [2 2 0 2 1]
B =  [1 0 2 3 3]
False
```

In [35]:
import numpy as np
A = [2, 2, 0, 2, 1]
B = [1, 0, 2, 3, 3]

print(np.all(A==B))

False


### Exe. 8
Considere uma matriz aleatória de 10x2 que representa coordenadas cartesianas, converta-as em coordenadas polares.

In [7]:
import numpy as np

ma = np.random.rand(10,2)
mp = np.array([np.sqrt(ma[:,0]*ma[:,0] + ma[:,1]*ma[:,1]), np.arctan2(ma[:,0],ma[:,1])]).T

print('Matriz original:')
print(ma)
print('Matriz polar (abs rad):')
print(mp)

Matriz original:
[[0.56829638 0.08525298]
 [0.32352595 0.29937833]
 [0.12696194 0.56039727]
 [0.69242015 0.0538566 ]
 [0.91995464 0.56530957]
 [0.57101722 0.69318614]
 [0.10345961 0.97754638]
 [0.08317548 0.10020284]
 [0.15968475 0.40378006]
 [0.41821997 0.40395223]]
Matriz polar:
[[0.57465542 1.42189172]
 [0.44079068 0.82414494]
 [0.57459937 0.22279595]
 [0.69451148 1.49317239]
 [1.07976453 1.01978525]
 [0.89809114 0.68906023]
 [0.98300601 0.10544348]
 [0.13022584 0.69280996]
 [0.43420911 0.37659908]
 [0.58145107 0.80275012]]


### Exe. 9
Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor.

Exemplo:
```
Zorg =  [1 2 3 4 5]
Z000 =  [ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]
```

In [9]:
import numpy as np

Zorg = np.array([1, 2, 3, 4, 5])
Z000 = np.zeros(Zorg.shape[0]*4 - 3)
Z000[::4] = Zorg

print('Z000 =',Z000)

Z000 = [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


### Exe. 10
Encontre o valor mais próximo de um dado valor em um array.

Exemplo:
```
Z =  [0.198 0.825 0.057 0.695 0.0333 0.793 0.526 0.547 0.787  0.656]
valor =  0.5
valor proximo em Z = 0.526929001754
```

In [14]:
import numpy as np

Z = np.random.rand(10) # pode também ser utilizado
# Z = np.array([0.198, 0.825, 0.057, 0.695, 0.0333, 0.793, 0.526, 0.547, 0.787, 0.656])
valor = 0.5

print('Z =', Z)
print('Valor próximo em Z =', Z[np.argmin(np.abs(Z - valor))])

Z = [0.32488443 0.65100676 0.12679017 0.19735557 0.0293183  0.14532546
 0.38191871 0.8476697  0.54467516 0.17553996]
Valor próximo em Z = 0.544675159497436


## Exercícios de Programação <a name="ExerProgramacao"></a>

### Exe. 1

Como encontrar o valor mais freqüente em um array?

Exemplo:
```
Z = [8 1 8 1 9 6 2 7 0 1 7 1 6 7 9 6 0 2 1 9 8 9 0 6 9 7 1 4 2 8 1 6 4 6 1 3 5 0 1 1 5 5 0 9 4 9 9 1 1 2]
ValMoreFreq = 1
```

In [18]:
import numpy as np

Z = np.random.randint(10, size=50)

print('Z =', Z)
aux = np.unique(Z, return_counts=True)
print('Valor mais frequente =', aux[0][np.argmax(aux[1])])

Z = [8 8 4 8 4 7 9 2 2 7 4 2 4 6 2 4 2 8 4 4 2 7 6 3 4 5 6 8 7 8 1 9 9 9 6 3 9
 4 9 8 9 0 5 4 3 6 7 1 2 9]
Valor mais frequente = 4


### Exe. 2

Considere duas matrizes A e B de forma (8,3) e (2,2). Como encontrar as linhas de A que contêm elementos de cada linha de B independentemente da ordem dos elementos em B? 

Exemplo:
```
A = [[2 1 4]
     [3 2 2]
     [3 4 1]
     [3 0 0]
     [4 3 4]
     [0 0 1]
     [2 1 4]
     [0 3 1]]
B = [[1 4]
     [2 4]]
rows = [0 1 2 4 6]
```

In [22]:
import numpy as np

A = np.array([[2, 1, 4], [3, 2, 2], [3, 4, 1], [3, 0, 0], [4, 3, 4], [0, 0, 1], [2, 1, 4], [0, 3, 1]])
B = np.array([[1,4], [2,4]])

c = np.isin(A,B)

print('rows =',np.arange(A.shape[0])[np.logical_or(np.logical_or(np.logical_and(c[:,0],c[:,1]),np.logical_and(c[:,0],c[:,2])), np.logical_and(c[:,1],c[:,2]))])

# a solução, segundo a questão como foi formulada, deveria retornar [0 2 6], e é apresentada abaixo
# print(np.arange(A.shape[0])[list(map(lambda x: ((B[0,0] in x) and (B[0,1] in x)) or ((B[1,0] in x) and (B[1,1] in x)),A))])

rows = [0 1 2 4 6]


### Exe. 3
Dado um array bidimensional, como extrair linhas unicas?

Exemplo:
```
Z = [[0 0 1]
     [1 0 0]
     [1 1 0]
     [1 1 1]
     [0 1 1]
     [1 1 0]]
Zu = [[0 0 1]
      [0 1 1]
      [1 0 0]
      [1 1 0]
      [1 1 1]]
```

In [25]:
import numpy as np

Z = np.array([[0, 0, 1],[1, 0, 0],[1, 1, 0],[1, 1, 1],[0, 1, 1],[1, 1, 0]])
Zs = np.array(list(map(str,Z)))

print(Z[np.unique(Zs, return_index=True)[1]])

[[0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


### Exe. 4
Converter um vetor de inteiros em uma matriz que seja sua representação binária.

Exemplo:
```
I = [0 1 2 3 15 16 32 64 128]
B = [[0 0 0 0 0 0 0 0]
     [0 0 0 0 0 0 0 1]
     [0 0 0 0 0 0 1 0]
     [0 0 0 0 0 0 1 1]
     [0 0 0 0 1 1 1 1]
     [0 0 0 1 0 0 0 0]
     [0 0 1 0 0 0 0 0]
     [0 1 0 0 0 0 0 0]
     [1 0 0 0 0 0 0 0]]
```

In [26]:
import numpy as np

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
Ir = I.reshape(I.shape[0],1)
B = np.unpackbits(Ir, axis=1)

print('B =', B)

B = [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


### Exe. 5
Considerando uma matriz 10x3, extraia linhas com valores desiguais (por exemplo, [2,2,3])

Exemplo:
```
Z = [[2 2 0]
     [1 1 3]
     [4 3 3]
     [1 0 1]
     [2 2 2]
     [2 3 3]
     [1 1 0]
     [0 2 0]
     [4 4 0]
     [4 2 3]]
Zd = [[2 2 0]
      [1 1 3]
      [4 3 3]
      [1 0 1]
      [2 3 3]
      [1 1 0]
      [0 2 0]
      [4 4 0]
      [4 2 3]]
```

In [28]:
import numpy as np

Z = np.array([[2,2,0],[1,1,3],[4,3,3],[1,0,1],[2,2,2],[2,3,3],[1,1,0],[0,2,0],[4,4,0],[4,2,3]])
# Zd = np.array([[2, 2, 0],[1, 1, 3],[4, 3, 3],[1, 0, 1],[2, 3, 3],[1, 1, 0],[0, 2, 0],[4, 4, 0],[4, 2, 3]])

d = list(map(lambda x: (x[0] == x[1]) and (x[1] == x[2]), Z))

print(Z[np.logical_not(d)])

[[2 2 0]
 [1 1 3]
 [4 3 3]
 [1 0 1]
 [2 3 3]
 [1 1 0]
 [0 2 0]
 [4 4 0]
 [4 2 3]]


## Exercícios de Vetorização <a name="ExerVetor"></a>

### Exe. 1
Sejam $𝐴$ e $𝐵$ matrizes de tamanho $10 \times 100$, calcule a **distância cosseno** entre suas as respectivas linhas. 
 * Não deve ser usado nenhum tipo de laço iterativo nem a biblioteca do `scikitlearn`. 
 * Tudo deve ser feito de forma matricial. 
 
A **distância cosseno** entre as linhas $i$-ésimas das matrizes $𝐴$ e $𝐵$ é dada pela expressção:
$$
𝑑_{c}=1 − 𝑐𝑜𝑠(a_{𝑖,:},b_{𝑖,:})
$$

Exemplo:
```
A = np.ones((10,100))  
B = np.reshape(np.arange(10*100),(10,100))
dist_cos = [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
 0.00098615 0.00074083 0.00057682 0.0004618 ]

```

In [6]:
import numpy as np
import math

A = np.ones((10,100))  
B = np.reshape(np.arange(10*100),(10,100))

dc = 1 - A.dot(B.T)/(np.linalg.norm(A,axis=1) * np.linalg.norm(B,axis=1))
print(dc)

[[0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615 0.00074083 0.00057682 0.0004618 ]
 [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
  0.00098615