# "OLÁ MUNDO" (*HELLO WORLD*) DO TENSOR FLOW </font></h1>


**NOTEBOOK CRIADO POR:** <a href="https://ca.linkedin.com/in/rafaelblsilva"> Rafael Belo Da Silva </a></h4> 

**TRADUÇÃO**: <a href="https://br.linkedin.com/in/thaispedruzzi"> Thais Pedruzzi do Nascimento </a></h4>


<div class="alert alert-block alert-info" style="margin-top: 20px">
<font size = 3><strong>Neste *notebook* nós iremos dar uma visão geral do TensorFlow, aprender suas estruturas e entender  motivação para usá-lo</strong></font>
<br>
- <p><a href="#ref2">Como o TensorFlow funciona?</a></p>
- <p><a href="#ref3">Construindo um Grafo</a></p>
- <p><a href="#ref4">Definindo uma matriz (*array*) multidimensional usando o TensorFlow</a></p>
- <p><a href="#ref5">Por que tensores?</a></p>
- <p><a href="#ref6">Variáveis</a></p>
- <p><a href="#ref7">*Placeholders*</a></p>
- <p><a href="#ref8">Operações</a></p>
<p></p>
</div>
<br>

----------------

<a id="ref2"></a>
# Como o TensorFlow unciona?

A capacidade do TensorFlow **de executar o código em diferentes dispositivo como CPUs e GPUS** é uma consequência da sua estrutura específica. 


O TensorFlow define cálculos (*computations*) como Grafos , que são feitas como operações (também conhecidas como "ops"). Então, trabalhar com TensorFlow **é o mesmo que definir uma série de operaçõs em um Grafo**. 

Para executar tais operações como *computations*, temos que iniciar o Grafo em uma Sessão (*Session*).  A sessão traduz e passa as operacões representadas nos grafos para o dispositivo onde elas serão executadas, seja ele uma GPU ou CPU.

Por exemplo, a imagem abaixo representa um grafo em TensorFlow. 
* `W`, `x` e `b` são tensores sobre as arestas deste grafo
* `MatMul` é uma operação sobre os tensores `W` e `x`, 
* depois disso, `Add` é chamada e soma o resultado da operação anterior a `b`.

Os tensores resultantes de cada operação passam pela próxima até o fim, onde é se possível obter o resultado desejado.

<img src='https://drive.google.com/uc?id=1omVg6oqxUzMYXuvWcVEAQs_qXQkmuD55'>


### Importando o TensorFlow
Para usar o TensorFlow, temos que importar a biblioteca. Depois de importá-la damos a ela, opcionalmente, o nome `tf`, de forma que os módulos possam ser acessados pelo comando `tf.nome-do-modulo`

In [0]:
import tensorflow as tf

-----------------

# Construindo um Grafo

Como dito anteriormente, o TensorFlow funciona como um modelo computacional de grafo. Vamos criar nosso primeiro grafo.

Para criar o nosso primeiro grafo, vamos utilizar **operações de origem** (***source operations***), que não precisam de nenhuma informação de entrada. 

* Tais operações de origem ou ***source ops*** passarão suas informações para outras operações que executarão cálculos (ou **computations**)

Para criar duas operações de origem que emitirão números, definiremos duas constantes:

In [0]:
a = tf.constant([2])
b = tf.constant([3])

Depois disso, vamos executar uma operação sobre essas varáveis. A função **tf.add()** soma dois elementos (poderíamos utilizar também `c = a + b`).

In [0]:
c = tf.add(a,b)
#c = a + b também é uma forma de definir soma de termos

Depois o TensorFlow precisa inicializar a sessão para executar o código. **Sessões são, de certa forma, um contexto para criar um grafo dentro do TensorFlow**. Vamos definir uma sessão:

In [0]:
session = tf.Session()

Vamos executar a sessão para obter o resultado da operação `c` definida anteriormente:

In [0]:
result = session.run(c)
print(result)

[5]


Fechamos a sessão para liberar recurso:


In [0]:
session.close()

---
**DICA**: Para evitar a necessidade de fechar sessões o tempo todo, pode definí-las em num bloco __with__ e depois de rodar o bloco  __with__ a sessão fechará automaticamente:

In [0]:
with tf.Session() as session:
    result = session.run(c)
    print(result)

[5]


---
Até mesmo esse exemplo bobo de somar 2 constantes para alcançar um simples resultado define a base do TensorFlow. 
Defina suas arestas (neste caso, nossas constantes), inclua nós (operaçãoes, como `tf.add`) e comece uma sessão para construir um grafo. 


### Qual o significado de Tensor?

**No TensorFlow todos os dados passam entre as operações em um grafo computacional. Tais dados são transmitidos em forma de Tensores, daí o nome  "TensorFlow".**

A palavra **tensor** do Neolatim significa "aquilo que estica". Um objeto matemático pode ser chamado **tensor** porque uma das primeiras aplicações de tensores foi o estudo de materiais que apresentavam elasticidade sob tensão mecânica. O significado contemporâneo de tensor pode ser dado como **vetores multidimensionais** (***multidimensional arrays***) 


Ótimo, mas...o que são vetores multidimensionais? 


Voltando à física para entender o conceito de dimensões:<br>
<img src="https://drive.google.com/uc?id=1ZT8PyBwcNvqU2RqTD6a3dRfdwRAV6ORD"/>
<div style="text-align:center">[[Image Source]](https://en.wikipedia.org/wiki/Dimension) </div>

1.A **dimensão zero** pode ser vista com um **ponto**, um único objeto ou um único item.
2. A **primeira dimensão** pode ser vista como uma **linha**, um vetor unidimensional, ou pontos ao longo desta linha. Uma dimensão pode conter infinitos pontos/elementos de dimensão zero. 
3. A **segunda dimensão** pode ser vista como uma **superfície**, um vetor bidimensional pode ser enxergado como uma série infinita de linhas ao longo de uma linha infinita.
4. A **terceira dimensão** pode ser vista como um **volume**, um vetor tridimensional pode ser visto como uma série infinita de superfícies ao longo de uma linha infinita.
5. A **quarta dimensão** pode ser vista como o **hiperespaço** ou **espaço-tempo**, um volume variando no tempo, ou uma série infinita de volumes ao longo de uma linha infinita. E assim sucessivamente...

Como objetos matemáticos: <br><br>
<img src="https://ibm.box.com/shared/static/kmxz570uai8eeg6i6ynqdz6kmlx1m422.png">
<div style="text-align:center">[[Image Source]](https://book.mql4.com/variables/arrays)</div>

Resumindo:<br><br>
<table style="width:100%">
  <tr>
    <td><b>Dimensão</b></td>
    <td><b>Representação Física</b></td> 
    <td><b>Objeto Matemático</b></td>
    <td><b>Em código</b></td>
  </tr>

  <tr>
    <td>Zero </td>
    <td>Ponto</td> 
    <td>Escalar (Número único)</td>
    <td>[ 1 ]</td>
  </tr>

  <tr>
    <td>Uma</td>
    <td>Linha</td> 
    <td>Vetor (Série de números) </td>
    <td>[ 1,2,3,4,... ]</td>
  </tr>
  
   <tr>
    <td>Duas</td>
    <td>Superfície</td> 
    <td>Matriz (Tabela de Números)</td>
    <td>[ [1,2,3,4,...], [1,2,3,4,...], [1,2,3,4,...],... ]</td>
  </tr>
  
   <tr>
    <td>Três</td>
    <td>Volume</td> 
    <td>Tensor (Cubo de Números)</td>
    <td>[ [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...],...], [[1,2,...], [1,2,...], [1,2,...] ,...]... ]</td>
  </tr>
  
</table>

-----------------

<a id="ref4"></a>
# Definindo vetores multidimensionais usando o TensorFlow
Agora vamos definir tais vetores usando o TensorFlow:

In [0]:
Scalar = tf.constant([2])
Vector = tf.constant([5,6,2])
Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session() as session:
    result = session.run(Scalar)
    print("Escalar (1 entrada):\n %s \n" % result)
    result = session.run(Vector)
    print("Vetor (3 entrada) :\n %s \n" % result)
    result = session.run(Matrix)
    print("Matriz (3x3 entradas):\n %s \n" % result)
    result = session.run(Tensor)
    print("Tensor (3x3x3 entradas) :\n %s \n" % result)

Escalar (1 entrada):
 [2] 

Vetor (3 entrada) :
 [5 6 2] 

Matriz (3x3 entradas):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entradas) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



Agora que você já entende a estrutura destes dados, te encorajo a brincar com eles usando algumas das funções anteriores para ver como vão se comportar, de acordo com cada tipo de estrutura:

In [0]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

first_operation = tf.add(Matrix_one, Matrix_two)
second_operation = Matrix_one + Matrix_two

with tf.Session() as session:
    result = session.run(first_operation)
    print("Definida utilizando função tensorflow:")
    print(result)
    result = session.run(second_operation)
    print("Definida utilizando expressões normais :")
    print(result)

Definida utilizando função do tensorflow:
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Definida utilizando expressões normais :
[[3 4 5]
 [4 5 6]
 [5 6 7]]


Em TensorFlow o símbolo regular de multiplicação efetua uma multiplicação ponto-a-ponto, também conhecida como **Produto de Hadamard**.

Mas e se quisermos obter o produto matricial regular?

Precisamos, então, utilizar outra função TensorFlow chamada `tf.matmul()`:

In [3]:
Matrix_one = tf.constant([[2,3],[3,4]])
Matrix_two = tf.constant([[2,3],[3,4]])

first_operation = tf.matmul(Matrix_one, Matrix_two)
second_operation = Matrix_one * Matrix_two


with tf.Session() as session:
    result = session.run(first_operation)
    print("Definida utilizando função tensorflow - Produto Comum de Matrizes:")
    print(result)
    result = session.run(second_operation)
    print("Definida utilizando expressões normais - Produto Hadamart:")
    print(result)

Definida utilizando função tensorflow - Produto Comum de Matrizes:
[[13 18]
 [18 25]]
Definida utilizando expressões normais - Produto Hadamart:
[[ 4  9]
 [ 9 16]]


Podemos, também, definir nós mesmo essa multiplicação, mas se já existe uma função que faz isso, não tem porquê reinventar a roda!

<a id="ref5"></a>
# Por que tensores?

A estrutura de Tensores nos ajuda nos dando liberdade para formatar o dataset (conjunto de dados) do jeito que desejarmos. 

E é particularmente útil ao se lidar com imagens, por causa da natureza de como as informações são codificadas. 

Pensando em imagens, é fácil entender que existem os parâmetros de altura e largura, então faria sentido representar tais informações em uma estrutura bidimensional (uma matriz)...até que você lembra que imagem tem cores, e para adicionar informação sobre cores, precisamos de uma outra dimensão, e é nesse momento que os Tensores se tornam particularmente úteis. 

Imagens são codificadas em canais de cores, os dados de imagens são representados por cada intensidade de cor em canal de cor em um dado ponto. Sendo que o canal de cor mais comum é o RGB, que significa *Red* (vermelho), *Green* (verde) e *Blue* (azul). As informações contidas em um imagem são intensidades de cores de cada canal de cor no espaço da altura e largura da imagem, da seguinte forma:

<img src='https://drive.google.com/uc?id=1z3fyB5xwIBIKWd3X90XOcnYXfpq0y1zi'>
<div style="text-align:center">[[Fonte da Imagem]](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424131.aspx)</div>

Então, a intensidade do canal vermelho em dado ponto com dadas larguras e altura podem pode ser representada em uma matriz, da mesma forma que os canais azul e verde. Ou seja, acabamos obtendo três matrizes e quando elas são combinadas temos um tensor. 


-----------------

<a id="ref6"></a>
# Variáveis

Agora que estamos mais familiarizados com a estrutura dos dados, *vamos dar uma olhada em como o TensorFlow manipula variáveis*.

* Para definir uma variável utilizamos o comando __tf.variable()__
* Para podermos utilizar variáveis em um grafo computacional (*computation graph*) devemos inicializá-las antes de rodar o grafo em uma sessão
  * Isso é feito rodando o comando __tf.global_variables_initializer()__.


Para atualizar o valor de uma variável, podemos simplesmente executar uma operação de atribuição (*assign operation*) que atribue um valor para a variável:

In [0]:
*state = tf.Variable(0)

Primeiro vamos criar um contador simples, uma variável que cresce uma unidade por vez:

In [0]:
one = tf.constant(1)
new_value = tf.add(state, one)
update = tf.assign(state, new_value)

Variáveis devem ser inicializadas executando-se uma operação de inicialização depois que o grafo foi iniciado. Primeiro temos que adicionar a operação de inicialização ao grafo:

In [0]:
init_op = tf.global_variables_initializer()

Então, começamos uma sessão para executar o grafo, inicializando as variáveis e, então, imprimimos o valor inicial da variável __state__. Depois, executamos a operação de atualização de __state__ e imprimos o resultado após cada atualização:

In [0]:
with tf.Session() as session:
  session.run(init_op)
  print(session.run(state))
  for _ in range(3):
    session.run(update)
    print(session.run(state))

0
1
2
3


-----------------

<a id="ref7"></a>
# *Placeholders*

Agora sabemos como manipular variáveis dentro do TensorFlow, **mas como fornecer dados externos a um modelo TensorFlow?**

Para fornecer dados externos para um modelo TensorFlow , devemos utilizar *placeholders*.

Mas o que são estes *placeholders* e o que eles fazem?

* *Placeholders* podem ser vistos como "buracos" no seu modelo, "buracos" por onde dados serão transmitidos. Eles podem ser criados utilizando-se <br/> <b>tf.placeholder(_datatype_)</b>, onde <b>_datatype_</b> espefica o tipo dos dados (inteiros, pontos flutuantes, strins, boleanos) junto com os bits de precisão (8, 16, 32, 64).

A definicação de cada tipo de dado com as respectivas sintaxes, em Python, é dada como:

|Tipo de dado	|Tipo, em Python|Descrição|
| --------- | --------- | --------- |
|DT_FLOAT	|tf.float32	|Ponto flutuante de 32 bits.|
|DT_DOUBLE	|tf.float64	|Ponto flutuante de 64 bits.|
|DT_INT8	|tf.int8	|Inteiro, com sinal, de 8 bits.|
|DT_INT16	|tf.int16	|Inteiro, com sinal, de 16 bits.|
|DT_INT32	|tf.int32	|Inteiro, com sinal, de 32 bits.|
|DT_INT64	|tf.int64	|Inteiro, com sinal, de 64 bits.|
|DT_UINT8	|tf.uint8	|Inteiro, sem sinal, de 8 bits.|
|DT_STRING	|tf.string	|Variable length byte arrays. Each element of a Tensor is a byte array.|
|DT_BOOL	|tf.bool	|Booleano.|
|DT_COMPLEX64	|tf.complex64	|Número complexo formado por dois pontos fluantes de 32 bits: partes real e imaginária.|
|DT_COMPLEX128	|tf.complex128	|Número complexo formado por dois pontos fluantes de 64 bits: partes real e imaginária.|
|DT_QINT8	|tf.qint8	|Inteiro, com sinal, de 8 bits utilizado em operação (ops) quantizadas.|
|DT_QINT32	|tf.qint32	|Inteiro, com sinal, de 32 bits utilizado em operação (ops) quantizadas.|
|DT_QUINT8	|tf.quint8	|Inteiro, sem sinal, de 8 bits utilzado em operação (ops) quantizadas.|

<div style="text-align:center">[[Fonte da tabela]](https://www.tensorflow.org/versions/r0.9/resources/dims_types.html)</div>


Criamos, então, um *placeholder*:

In [0]:
a=tf.placeholder(tf.float32)

E definos a operação de multiplicação simples:

In [0]:
b=a*2

Precisamos, agora, definir e executar a sessão, mas como criamos um "buraco" no modelo para transmistir os dados, como **iniciamos a sessão somos obrigador a passar um argumento com os dados, caso contrário um erro será retornado**.

Para passar os dados para o modelo, chamamos a sessão comum argumento extra `feed_dict` no qual podemos passar o dicionário com cada nome dos *placeholders* seguido dos dados referentes a ele, da seguinte forma:

In [0]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print(result)

7.0


Como os dados no TensorFlor são passados na forma de vetores multidimensionais, podemos passar qualquer tipo de tensor através dos *placeholders* para obter a resposta da operação de multiplicação simples:

In [0]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


-----------------

<a id="ref8"></a>
# Operações

Operações são nós que representam as operação matemáticas sobre os tensores em um grafo. Tais operações podem ser qualquer tipo de função, como somar ou subtrair tensores ou talvez funções de ativações. 

_tf.matmul_, _tf.add_, _tf.nn.sigmoid_ são algumas operação possíveis em TensorFlow. Elas são tipo funções em Python mas operam diretamente sobre tensores e cada uma faz uma coisa específica. 
_tf.matmul_, _tf.add_, _tf.nn.sigmoid_ are some of the operations in TensorFlow. These are like functions in python but operate directly over tensors and each one does a specific thing. 

<div class="alert alert-success alertsuccess" style="margin-top: 20px"> Outras operações podem ser encontradas em: https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html</div>

In [0]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)

with tf.Session() as session:
    result = session.run(c)
    print('c =: %s' % result)
    result = session.run(d)
    print('d =: %s' % result)

c =: [7]
d =: [3]


_tf.nn.sigmoid_ é uma função de ativação, o que é um pouco mais complicado, mas essa função auxilia modelos de treinamento a avaliar que tipo de informação é boa ou não.

-----------------

## Quer aprender mais?

Executar programas de aprendizado profundo normalmente requer uma plataforma de alta perfomance. PowerAI acelera aprendizado profundo e AI. Criado em Power Systems, da IBM, PowerAI é uma plataforma de software expansível para acelerar aprendizado profundo e AI com desempenho esplendoroso para usuários individuais ou empresas. A plataforma PowerAI suporta bibliotecas populares de aprendizado de máquinas e dependência que inclue Tensorflor, Caffe, Torch e Theano. Você pode baixar uma [versão gratuita da PowerAI](https://cocl.us/ML0120EN_PAI).

Além disso, você pode utilizar a Data Science Experience para executar esses notebooks mais rápido com datasets maiores. Data Science Experience é uma solução em nuvem de ponta da IBM para cientistas de dados, construída por cientistas de dados. Com notebooks Jupyter, RStudio, Apache Spark e bibliotecas popular pré-empacotadas (*pre-packaged*) na nivem, DSX viabiliza a colaboração de cientistas de dados em seus projetos sem ser necessário instalar nenhum pacote ou programa. Junte-se a essa comunidade em rápido crescimento de usuários DSX fazendo uma conta gratuita na [Data Science Experience](https://cocl.us/ML0120EN_DSX). Esse é o fim desta aula. This is the end of this lesson. Esperamos que, agora você tenha um entendimento intuitivo e mais profundo sobre o modelo LSTM. Obrigada por ler esse notebook e boa sorte em seus estudos :). 

### References:

https://www.tensorflow.org/versions/r0.9/get_started/index.html<br />
http://jrmeyer.github.io/tutorial/2016/02/01/TensorFlow-Tutorial.html<br />
https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html<br />
https://www.tensorflow.org/versions/r0.9/resources/dims_types.html<br />
https://en.wikipedia.org/wiki/Dimension<br />
https://book.mql4.com/variables/arrays<br />
https://msdn.microsoft.com/en-us/library/windows/desktop/dn424131(v=vs.85).aspx<br />

<hr>
Copyright &copy; 2016 [Big Data University](https://bigdatauniversity.com/?utm_source=bducopyrightlink&utm_medium=dswb&utm_campaign=bdu). This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license/).