# TensorFlow Operations

[TensorFlow はじめの一歩(3) ](http://mirai-tec.hatenablog.com/entry/2016/02/22/001459)

## Indicações <a name="indicacoes"></a>

### Mensagem
* Quem deseja participar na tradução deste tutorial, pode-me enviar um email a **jlasam001@gmail.com** informando sua disponibilidade para a tarefa de tradução. Cabe indicar que o aluno participante da tradução do documento ganhara 1 ponto extra.

### Dicas execução
* Carregue todos os pacotes que serão necessários no início do arquivo.
* Entre um exercício e outro, utilize um grafo diferente ou então reínicie o grafo padrão.
* Para executar comandos da shell dentro do notebook, utilize o prefixo `!` antes do comando de shell. (e.g. para listar os arquivos da pasta atual faça `! ls` para UNIX ou `! dir` para Windows.

In [0]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

## Arithmetic operation

|API|function|
|---|--------|
|`tf.add(x, y, name = None)` | Addition: x + y |
|`tf.subtract(x, y, name = None)` | Subtraction: x - y |
|`tf.multiply(x, y, name = None)` | Multiplication: x * y |
|`tf.div(x, y, name = None)` | Division: x / y |
|`tf.truediv(x, y, name = None)` | Division ( floating point number ): x / y |
|`tf.floordiv (x, y, name = None)` | Division (devaluation): x / y |
|`tf.mod (x, y, name = None)` |	Surplus: x%y |

---

In [2]:
################
# tf.add
################
x = tf.constant([1., 2.])
y = tf.constant([0.5, 0.5])
tf_add = tf.add(x, y)
print("tf.add")
with	tf.Session()	as	sess:	
  print(sess.run(tf_add))

tf.add
[1.5 2.5]


---

In [6]:
################
# tf.subtract
################
x = tf.constant([[1., 2.], [3., 4.]])
y = tf.constant([[0.5, 0.5], [1., 1.]])
tf_sub = tf.subtract(x, y)
print("tf.subtract")
with	tf.Session()	as	sess:	
  print(sess.run(tf_sub))

tf.sub
[[0.5 1.5]
 [2.  3. ]]


---

In [10]:
################
# tf.multiply
################
x = tf.constant([1., 2.])
y = tf.constant([[2.], [3.]])
tf_mul = tf.multiply(x, y)
print("tf.multiply")
with	tf.Session()	as	sess:	
  print(sess.run(tf_mul))

tf.multiply
[[2. 4.]
 [3. 6.]]


---

In [11]:
################
# tf.div
################
x = tf.constant([10, 15])
y = tf.constant([3])
tf_div = tf.div(x, y)
print("tf.div")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_div))

tf.div
[3 5]


---

In [12]:
################
# tf.truediv
################
x = tf.constant([10, 15])
y = tf.constant([3])
tf_truediv = tf.truediv(x, y)
print("tf.truediv")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_truediv))

tf.truediv
[3.33333333 5.        ]


---

In [13]:
################
# tf.floordiv
################
x = tf.constant([10., 15.])
y = tf.constant([3.])
tf_floordiv = tf.floordiv(x, y)
print("tf.floordiv")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_floordiv))

tf.floordiv
[3. 5.]


---

In [14]:
################
# tf.mod
################
x = tf.constant([10., 15.])
y = tf.constant([3.])
tf_mod = tf.mod(x, y)
print("tf.mod")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_mod))

tf.mod
[1. 0.]


## Basic Mathematical Functions

|API|function|
|---|--------|
| `tf.add_n(inputs, name = None)` |	Add all input Tensors by element |
| `tf. abs(x, name = None)` |	Calculate the absolute value of Tensor |
| `tf.negative(x, name = None)` |	Calculate half (-x) for each element |
| `tf.sign(x, name = None)` |	Returns the sign of a number for each element |
| `tf.reciprocal(x, name = None)` |	Calculate reciprocal (1 / x) for each element |
| `tf.square(x, name = None)` |	Compute the square (x ^ 2) for each element |
| `tf.round(x, name = None)` |	Returns rounded values ​​for each element |
| `tf.sqrt(x, name = None)` |	Calculate the square root (√x) for each element |
| `tf.rsqrt(x, name = None)` |	Compute reciprocal of square root (1 / √ x) for each element |
| `tf.pow(x, y, name = None)` |	Calculate exponentiation (x ^ y) for each element |
| `tf.exp(x, name = None)` |	Calculate the exponential function (e ^ x) for each element |
| `tf.log(x, name = None)` |	Calculate natural logarithm (log x) for each element |
| `tf.ceil(x, name = None)` |	Returns the smallest integer not less than x for each element |
| `tf.floor(x, name = None)` |	Returns the largest integer not exceeding x for each element |
| `tf.maximum(x, y, name = None)` |	Return maximum value for each element |
| `tf.minimum(x, y, name = None)` |	Return the minimum value for each element |
| `tf.cos(x, name = None)` |	Compute cosine (cos) for each element |
| `tf.sin(x, name = None)` |	Compute sine (sin) for each element|

---

In [16]:
################
# tf.add_n
################
a = tf.constant ([ 1. , 2. ])
b = tf.constant ([ 3. , 4. ])
c = tf.constant ([ 5. , 6. ])
tf_addn = tf.add_n ([a, b, c])
print("tf.add_n")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_addn))

tf.add_n
[ 9. 12.]


---

In [18]:
################
# tf.abs
################
x = tf.constant ([[- 1. , 2. ], [ 3. , - 4. ]])
tf_abs = tf. abs (x)
print("tf.abs")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_abs))

tf.abs
[[1. 2.]
 [3. 4.]]


---

In [20]:
################
# tf.negative
#######
x = tf.constant ([[- 1. , 2. ], [ 3. , - 4. ]])
tf_neg = tf.negative(x)
print("tf.negative")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_neg))

tf.negative
[[ 1. -2.]
 [-3.  4.]]


---

In [22]:
################
# tf.sign
################
x = tf.constant ([[- 1. , 2. ], [ 3. , - 4. ]])
tf_sign = tf.sign (x)
print("tf.sign")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_sign))

tf.sign
[[-1.  1.]
 [ 1. -1.]]


---

In [24]:
################
# tf.reciprocal
################
x = tf.constant ([[- 1. , 2. ], [ 3. , - 4. ]])
tf_reciprocal = tf.reciprocal(x)
print("tf.reciprocal")
with	tf.Session()	as	sess:	   
  print(sess.run(tf_reciprocal))

tf.reciprocal
[[-1.          0.5       ]
 [ 0.33333334 -0.25      ]]


---

In [25]:
################
# tf.square
################
x = tf.constant ([[- 1. , 2. ], [ 3. , - 4. ]])
tf_square = tf.square (x)
print("tf.square")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_square))

tf.square
[[ 1.  4.]
 [ 9. 16.]]


---

In [26]:
################
# tf.round
################
x = tf.constant ([ 0.9 , 2.5 , 2.3 , - 4.4 ])
tf_round = tf. round (x)
print("tf.round")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_round))

tf.round
[ 1.  2.  2. -4.]


---

In [27]:
################
# tf.sqrt
################
x = tf.constant ([[ 1. , 2. ], [ 3. , 4. ]])
tf_sqrt = tf.sqrt (x)
print("tf.sqrt")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_sqrt))

tf.sqrt
[[1.        1.4142135]
 [1.7320508 2.       ]]


---

In [28]:
################
# tf.rsqrt
################
x = tf.constant ([[ 1. , 2. ], [ 3. , 4. ]])
tf_rsqrt = tf.rsqrt (x)
print("tf.rsqrt")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_rsqrt))

tf.rsqrt
[[1.         0.70710677]
 [0.57735026 0.5       ]]


---

In [29]:
################
# tf.pow
################
x = tf.constant ([[ 2 , 2 ], [ 3 , 3 ]])
y = tf.constant ([[ 8 , 16 ], [ 2 , 3 ]])
tf_pow = tf. pow (x, y)
print("tf.pow")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_pow))

tf.pow
[[  256 65536]
 [    9    27]]


---

In [30]:
################
# tf.exp
################
x = tf.constant ([[ 1. , 2. ], [ 3. , 4. ]])
tf_exp = tf.exp (x)
print("tf.exp")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_exp))

tf.exp
[[ 2.7182817  7.389056 ]
 [20.085537  54.59815  ]]


---

In [31]:
################
# tf.log
################
x = tf.constant ([[ 1. , 2. ], [ 3. , 4. ]])
tf_log = tf.log(x)
print("tf.log")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_log))

tf.log
[[0.        0.6931472]
 [1.0986123 1.3862944]]


---

In [0]:
################
# tf.ceil
################
x = tf.constant ([[[ 1.1 , 2.2 ], [ 3.3 , 4.4 ]])
tf_ceil = tf.ceil (x)
print "tf.ceil"
with	tf.Session()	as	sess:	                    
print sess.run (tf_ceil)

---

In [33]:
################
# tf.floor
################
x = tf.constant ([[ 1.1 , 2.2 ], [ 3.3 , 4.4 ]])
tf_floor = tf.floor(x)
print("tf.floor")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_floor))

tf.floor
[[1. 2.]
 [3. 4.]]


---

In [34]:
################
# tf.maximum
################
x = tf.constant ([[ 2 , 8 ], [ 3 , 12 ]])
y = tf.constant ([[ 4 , 10 ], [ 1 , 9 ]])
tf_maximum = tf.maximum(x, y)
print("tf.maximum")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_maximum))

tf.maximum
[[ 4 10]
 [ 3 12]]


---

In [35]:
################
# tf.minimum
################
x = tf.constant([[ 2 , 8 ], [ 3 , 12 ]])
y = tf.constant([[ 4 , 10 ], [ 1 , 9 ]])
tf_minimum = tf.minimum(x, y)
print("tf.minimum")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_minimum))

tf.minimum
[[2 8]
 [1 9]]


---

In [37]:

################
# tf.cos
################
x = tf.constant ([[ 2. , 8. ], [ 3. , 12. ]])
tf_cos = tf.cos (x)
print("tf.cos")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_cos))

tf.cos
[[-0.41614684 -0.14550003]
 [-0.9899925   0.84385395]]


---

In [38]:
################
# tf.sin
################
x = tf.constant ([[ 2. , 8. ], [ 3. , 12. ]])
tf_sin = tf.sin (x)
print("tf.sin")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_sin))

tf.sin
[[ 0.9092974   0.98935825]
 [ 0.14112    -0.53657293]]


## Matrix operation function

|API|function|
|---|--------|
| `tf.diag (diagonal, name = None)` |	Return a Tensor with a diagonal component |
| `tf.transpose (a, perm = None, name = transpose)` |	Swap rows and columns |
| `tf.matmul (a, b, transpose_a = False, transpose_b = False, a_is_sparse = False, b_is_sparse = False, name = None)` |	Calculate matrix product |
| `tf.batch_matmul (x, y, adj_x = None, adj_y = None, name = None)` |	Calculate Tensor matrix slice products |
| `tf.matrix_determinant (input, name = None)` |	Compute determinant of square matrix |
| `tf.batch_matrix_determinant (input, name = None)` |	Calculate determinant of Tensor 's square matrix slice |
| `tf.matrix_inverse (input, name = None)` |	Calculate inverse matrix of square matrix |
| `tf.batch_matrix_inverse (input, name = None)` |	Calculate the inverse matrix of Tensor 's square matrix slice |
| `tf.cholesky (input, name = None)` |	Calculate Cholesky decomposition of square matrix |
| `tf.batch_cholesky (input, name = None)` |	Calculate Cholesky decomposition of Tensor 's square matrix slice |
| `tf.self_adjoint_eig (input, name = None)` |	Compute eigenvalue decomposition of Hermitian matrix |
| `tf.batch_self_adjoint_eig (input, name = None)` |	Compute eigenvalue decomposition of Hermitian matrix slices of Tensor |

---

In [45]:
################################
# tf.diag
################################
# 'diagonal' is [1, 2, 3, 4]
tf_diag = tf.diag ([ 1 , 2 , 3 , 4 ])
print("tf.diag")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_diag))

tf.diag
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


---

In [46]:
################################
# tf.transpose
################################
# 'x' is [[1 2 3]
# [4 5 6]]
x = tf.constant ([[ 1 , 2 , 3 ], [ 4 , 5 , 6 ]])
tf_trans = tf.transpose (x)
print("tf.transpose")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_trans))

tf.transpose
[[1 4]
 [2 5]
 [3 6]]


---

In [49]:
print('Equivalently')
tf_trans = tf.transpose (x, perm = [ 1 , 0 ])
with tf.Session()	as	sess:	  
  print(sess.run (tf_trans))


Equivalently
[[1 4]
 [2 5]
 [3 6]]


---

In [50]:
# 'perm' is more useful for n-dimensional tensors, for n> 2
# 'x' is [[[1 2 3]
# [4 5 6]]
# [[7 8 9]
# [10 11 12]]]
# Take the transpose of the matrices in dimension-0
x = tf.constant ([[[ 1 , 2 , 3 ], [ 4 , 5 , 6 ]], [[ 7 , 8 , 9 ], [ 10 , 11 , 12 ]]])
tf_trans = tf.transpose (x, perm = [ 0 , 2 , 1 ])
with tf.Session()	as	sess:	  
  print(sess.run (tf_trans))

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


---

In [44]:
################################
# tf.matmul
################################
# 2-D tensor `a`
a = tf.constant ([ 1 , 2 , 3 , 4 , 5 , 6 ], shape = [ 2 , 3 ])
# 2-D tensor `b`
b = tf.constant ([ 7 , 8 , 9 , 10 , 11 , 12 ], shape = [ 3 , 2 ])
tf_matmul = tf.matmul (a, b)

print("tf.matmul")
with	tf.Session()	as	sess:	  
  print(sess.run(tf_matmul))

tf.matmul
[[ 58  64]
 [139 154]]


---

In [40]:
################################
# tf.matrix_determinant
################################
a = tf.constant ([ 1. , 2. , 3. , 4. ], shape = [ 2 , 2 ])
tf_determinant = tf.matrix_determinant (a)

print("tf.matrix_determinant")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_determinant))

tf.matrix_determinant
-2.0


---

In [39]:
################################
# tf.matrix_inverse
################################
a = tf.constant ([ 1. , 2. , 3. , 4. ], shape = [ 2 , 2 ])
tf_inverse = tf.matrix_inverse (a)

print("tf.matrix_inverse")
with	tf.Session()	as	sess:	  
  print(sess.run (tf_inverse))

tf.matrix_inverse
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]


## Complex function

|API|function|
|---|--------|
| `tf.complex(real, imag, name = None)` |	Convert from real part / imaginary part to complex tensor |
| `tf.abs(x, name = None))` |	Compute the absolute value of a complex number (a + bj → √ (a ^ + b ^ 2)) |
| `tf.conj(in_, name = None))` |	Return complex conjugate (a + bj → a - bj) |
| `tf.imag(in_, name = None))` |	Returns the imaginary part of a complex number (a + bj → b) |
| `tf.real(in_, name = None))` |	Returns the real part (a + bj → a) of a complex number |

---

In [51]:
################
# tf.complex
################
# tensor 'real' is [2.25, 3.25]
# tensor `imag` is [4.75, 5.75]
tf_complex = tf. complex ([ 2.25 , 3.25 ], [ 4.75 , 5.75 ])
print("tf.complex")
with	tf.Session()	as	sess:
  print(sess.run(tf_complex))

tf.complex
[2.25+4.75j 3.25+5.75j]


---

In [53]:
################
# tf.abs
################
# tensor 'x' is [[-2.25 + 4.75 j], [-3.25 + 5.75 j]]
x = tf. complex ([- 2.25 , - 3.25 ], [ 4.75 , 5.75 ])
tf_abs = tf.abs(x)

print("tf.complex_abs")
with	tf.Session()	as	sess:
  print(sess.run(tf_abs))

tf.complex_abs
[5.255949  6.6049223]


---

In [54]:
################
# tf.conj
################
# tensor 'in' is [-2.25 + 4.75 j, 3.25 + 5.75 j]
x = tf. complex ([- 2.25 , 3.25 ], [ 4.75 , 5.75 ])
tf_conj = tf.conj (x)

print("tf.conj")
with	tf.Session()	as	sess:
  print(sess.run (tf_conj))

tf.conj
[-2.25-4.75j  3.25-5.75j]


---

In [55]:
################
# tf.imag
################
# tensor 'in' is [-2.25 + 4.75 j, 3.25 + 5.75 j]
x = tf. complex ([- 2.25 , 3.25 ], [ 4.75 , 5.75 ])
tf_imag = tf.imag (x)

print("tf.imag")
with tf.Session()	as	sess:
  print(sess.run (tf_imag))

tf.imag
[4.75 5.75]


---

In [67]:
################
# tf.real
################
# tensor 'in' is [-2.25 + 4.75 j, 3.25 + 5.75 j]
x = tf. complex ([- 2.25 , 3.25 ], [ 4.75 , 5.75 ])
tf_real = tf.real(x)

print("tf.real")
with	tf.Session()	as	sess:
  print(sess.run (tf_real))

tf.real
[-2.25  3.25]


## Reduction of tensor

|API|function|
|---|--------|
| `tf.reduce_sum (input_tensor, reduction_indices = None, keep_dims = False, name = None)` |	Compute the sum of elements of Tensor |
| `tf.reduce_prod (input_tensor, reduction_indices = None, keep_dims = False, name = None))` |	Calculate the product of Tensor 's elements |
| `tf.reduce_min (input_tensor, reduction_indices = None, keep_dims = False, name = None))` |	Compute minimum of Tensor 's elements |
| `tf.reduce_max (input_tensor, reduction_indices = None, keep_dims = False, name = None))` |	Calculate the maximum of Tensor 's elements |
| `tf.reduce_mean (input_tensor, reduction_indices = None, keep_dims = False, name = None))` |	Compute the average of the elements of Tensor |
| `tf.reduce_all (input_tensor, reduction_indices = None, keep_dims = False, name = None))` |	Compute the AND of elements of Tensor (and) |
| `tf.reduce_any (input_tensor, reduction_indices = None, keep_dims = False, name = None))` |	Calculate the logical sum (or) of elements of Tensor |
| `tf.accumulate_n (inputs, shape = None, tensor_dtype = None, name = None))` |	Compute the sum for each element of Tensor |

---

In [60]:
##################
# tf.reduce_sum
##################
# 'x' is [[1, 1, 1]]
# [1, 1, 1]]
x = tf.constant ([[ 1 , 1 , 1 ], [ 1 , 1 , 1 ]])
tf_rsum1 = tf.reduce_sum(x)
tf_rsum2 = tf.reduce_sum(x, 0 )
tf_rsum3 = tf.reduce_sum(x, 1 ) 
tf_rsum4 = tf.reduce_sum(x, 1 , keep_dims = True )
tf_rsum5 = tf.reduce_sum(x, [ 0 , 1 ])

print("tf.reduce_sum")
with	tf.Session()	as	sess:
  print(sess.run(tf_rsum1))
  print(sess.run(tf_rsum2))
  print(sess.run(tf_rsum3))
  print(sess.run(tf_rsum4))
  print(sess.run(tf_rsum5))

Instructions for updating:
keep_dims is deprecated, use keepdims instead
tf.reduce_sum
6
[2 2 2]
[3 3]
[[3]
 [3]]
6


---

In [63]:
##################
# tf.reduce_prod
##################
x = tf.constant ([[ 1 , 2 , 3 ], [ 1 , 2 , 3 ]])
tf_rprod1 = tf.reduce_prod(x)
tf_rprod2 = tf.reduce_prod(x, 0 )
tf_rprod3 = tf.reduce_prod(x, 1 )
tf_rprod4 = tf.reduce_prod(x, 1 , keep_dims = True )
tf_rprod5 = tf.reduce_prod(x, [ 0 , 1 ])

print("tf.reduce_prod")
with	tf.Session()	as	sess:
  print(sess.run(tf_rprod1))
  print(sess.run(tf_rprod2))
  print(sess.run(tf_rprod3))
  print(sess.run(tf_rprod4))
  print(sess.run(tf_rprod5))

Instructions for updating:
keep_dims is deprecated, use keepdims instead
tf.reduce_prod
36
[1 4 9]
[6 6]
[[6]
 [6]]
36


---

In [64]:
##################
# tf.reduce_min
##################
x = tf.constant ([[ 1 , 2 , 3 ], [ 1 , 2 , 3 ]])
tf_rmin1 = tf.reduce_min(x)
tf_rmin2 = tf.reduce_min(x, 0 ) #col
tf_rmin3 = tf.reduce_min(x, 1 ) #fil
tf_rmin4 = tf.reduce_min(x, 1 , keep_dims = True )
tf_rmin5 = tf.reduce_min(x, [ 0 , 1 ])

print("tf.reduce_min")
with	tf.Session()	as	sess:
  print(sess.run(tf_rmin1))
  print(sess.run(tf_rmin2))
  print(sess.run(tf_rmin3))
  print(sess.run(tf_rmin4))
  print(sess.run(tf_rmin5))

tf.reduce_min
1
[1 2 3]
[1 1]
[[1]
 [1]]
1


---

In [66]:
##################
# tf.reduce_max
##################
x = tf.constant ([[ 1 , 2 , 3 ], [ 1 , 2 , 3 ]])
tf_rmax1 = tf.reduce_max(x)
tf_rmax2 = tf.reduce_max(x, 0 ) # col
tf_rmax3 = tf.reduce_max(x, 1 ) # fil
tf_rmax4 = tf.reduce_max(x, 1 , keep_dims = True )
tf_rmax5 = tf.reduce_max(x, [ 0 , 1 ])

print("tf.reduce_max")
with	tf.Session()	as	sess:
  print(sess.run(tf_rmax1))
  print(sess.run(tf_rmax2))
  print(sess.run(tf_rmax3))
  print(sess.run(tf_rmax4))
  print(sess.run(tf_rmax5))

Instructions for updating:
keep_dims is deprecated, use keepdims instead
tf.reduce_max
3
[1 2 3]
[3 3]
[[3]
 [3]]
3


---

In [68]:
##################
# tf.reduce_mean
##################
# 'x' is [[1., 1.]]
# [twenty two.]]
x = tf.constant ([[ 1. , 1. ], [ 2. , 2. ]])
tf_rmean1 = tf.reduce_mean(x)
tf_rmean2 = tf.reduce_mean(x, 0 ) #col
tf_rmean3 = tf.reduce_mean(x, 1 ) #fil

print("tf.reduce_mean")
with	tf.Session()	as	sess:
  print(sess.run(tf_rmean1))
  print(sess.run(tf_rmean2))
  print(sess.run(tf_rmean3))


tf.reduce_mean
1.5
[1.5 1.5]
[1. 2.]


---

In [71]:
##################
# tf.reduce_all
##################
# 'x' is [[True, True]]
# [False, False]]
x = tf.constant ([[ True , True ], [ False , False ]])
tf_rall1 = tf.reduce_all(x)
tf_rall2 = tf.reduce_all(x, 0 ) #col
tf_rall3 = tf.reduce_all(x, 1 ) #fil

print("tf.reduce_all")
with	tf.Session()	as	sess:
  print(sess.run(tf_rall1))
  print(sess.run(tf_rall2))
  print(sess.run(tf_rall3))

tf.reduce_all
False
[False False]
[ True False]


---

In [72]:
##################
# tf.reduce_any
##################
# 'x' is [[True, True]]
# [False, False]]
x = tf.constant ([[ True , True ], [ False , False ]])
tf_rany1 = tf.reduce_any (x)
tf_rany2 = tf.reduce_any (x, 0 )
tf_rany3 = tf.reduce_any (x, 1 )

print("tf.reduce_any")
with	tf.Session()	as	sess:
  print(sess.run(tf_rany1))
  print(sess.run(tf_rany2))
  print(sess.run(tf_rany3))

tf.reduce_any
True
[ True  True]
[ True False]


---

In [74]:
##################
# tf.accumulate_n
##################
# tensor 'a' is [[1, 2], [3, 4]
# tensor `b` is [[5, 0], [0, 6]]
a = tf.constant([[ 1 , 2 ], [ 3 , 4 ]])
b = tf.constant([[ 5 , 0 ], [ 0 , 6 ]])
tf_accum1 = tf.accumulate_n([a, b, a])

# Explicitly pass shape and type
tf_accum2 = tf.accumulate_n([a, b, a], shape = [ 2 , 2 ], tensor_dtype = tf.int32)

print("tf.accumulate_n")
with	tf.Session()	as	sess:  
  print(sess.run(tf_accum1))
  print(sess.run(tf_accum2))

tf.accumulate_n
[[ 7  4]
 [ 6 14]]
[[ 7  4]
 [ 6 14]]


## Segment

|API|function|
|---|--------|
| `tf.segment_sum (data, segment_ids, name = None)` |	Compute the sum of each segment of Tensor |
| `tf.segment_prod (data, segment_ids, name = None)` |	Calculate the product of each segment of Tensor |
| `tf.segment_min (data, segment_ids, name = None)` |	Calculate minimum of each segment of Tensor |
| `tf.segment_max (data, segment_ids, name = None)` |	Calculate maximum of each segment of Tensor |
| `tf.segment_mean (data, segment_ids, name = None)` |	Calculate average of each segment of Tensor |
| `tf.unsorted_segment_sum (data, segment_ids, num_segments, name = None)` |	Compute the sum of each segment of Tensor |
| `tf.sparse_segment_sum (data, indices, segment_ids, name = None)` |	Compute the sum of selected segments of Tensor |
| `tf.sparse_segment_mean (data, indices, segment_ids, name = None)` |	Calculate the average of Tensor 's selected segment |

---

In [76]:
##########################
# tf.segment_sum
##########################
c = tf.constant ([[ 1 , 2 , 3 , 4 ], [- 1 , - 2 , - 3 , - 4 ], [ 5 , 6 , 7 , 8 ]])
tf_sum = tf.segment_sum(c, tf.constant([ 0 , 0 , 1 ]))

print("tf.segment_sum")
with	tf.Session()	as	sess:  
  print(sess.run(tf_sum))

tf.segment_sum
[[0 0 0 0]
 [5 6 7 8]]


---

In [78]:
##########################
# tf.segment_sum
##########################
c = tf.constant ([[ 1 , 2 , 3 , 4 ], [- 1 , - 2 , - 3 , - 4 ], [ 5 , 6 , 7 , 8 ]])
tf_sum = tf.segment_sum (c, tf.constant ([ 0 , 0 , 1 ]))

print("tf.segment_sum")
with tf.Session()	as	sess:  
  print(sess.run(tf_sum))

tf.segment_sum
[[0 0 0 0]
 [5 6 7 8]]


---

In [79]:
##########################
# tf.segment_min
##########################
c = tf.constant ([[ 1 , 2 , 3 , 4 ], [- 1 , - 2 , - 3 , - 4 ], [ 5 , 6 , 7 , 8 ]])
tf_min = tf.segment_min (c, tf.constant([ 0 , 0 , 1 ]))

print("tf.segment_min")
with	tf.Session()	as	sess:  
  print(sess.run(tf_min))

tf.segment_min
[[-1 -2 -3 -4]
 [ 5  6  7  8]]


---

In [80]:
##########################
# tf.segment_max
##########################
c = tf.constant ([[ 1 , 2 , 3 , 4 ], [- 1 , - 2 , - 3 , - 4 ], [ 5 , 6 , 7 , 8 ]])
tf_max = tf. segment_max (c, tf.constant ([ 0 , 0 , 1 ]))

print("tf.segment_max")
with	tf.Session()	as	sess:  
  print(sess.run (tf_max))

tf.segment_max
[[1 2 3 4]
 [5 6 7 8]]


---

In [81]:
##########################
# tf.segment_mean
##########################
c = tf.constant ([[ 1 , 2 , 3 , 4 ], [- 1 , - 2 , - 3 , - 4 ], [ 5 , 6 , 7 , 8 ]])
tf_mean = tf.segment_mean (c, tf.constant ([ 0 , 0 , 1 ]))

print("tf.segment_mean")
with	tf.Session()	as	sess:  
  print(sess.run(tf_mean))

tf.segment_mean
[[0 0 0 0]
 [5 6 7 8]]


---

In [82]:
##########################
# tf.unsorted_segment_sum
##########################
c = tf.constant ([[ 1 , 2 , 3 , 4 ], [- 1 , - 2 , - 3 , - 4 ], [ 5 , 6 , 7 , 8 ]])
tf_unsorted = tf.unsorted_segment_sum (c, tf.constant ([ 1 , 0 , 0 ]), 2 )

print("tf.unsorted_segment_sum")
with	tf.Session()	as	sess:  
  print(sess.run (tf_unsorted))

tf.unsorted_segment_sum
[[4 4 4 4]
 [1 2 3 4]]


---

In [86]:
##########################
# tf.sparse_segment_sum
##########################
c = tf.constant([[ 1 , 2 , 3 , 4 ], [- 1 , - 2 , - 3 , - 4 ], [ 5 , 6 , 7 , 8 ]])
 
# Select two rows, one segment.
tf_ssum1 = tf.sparse_segment_sum (c, tf.constant ([ 0 , 1 ]), tf.constant([ 0 , 0 ]))
# Select two rows, two segment.
tf_ssum2 = tf.sparse_segment_sum (c, tf.constant ([ 0 , 1 ]), tf.constant([ 0 , 1 ]))

# Select all rows, two segments.
tf_ssum3 = tf.sparse_segment_sum (c, tf.constant ([ 0 , 1 , 2 ]), tf.constant([ 0 , 0 , 1 ]))

print("tf.sparse_segment_sum")
with	tf.Session()	as	sess:  
  print(sess.run(tf_ssum1))
  print(sess.run(tf_ssum2))
  print(sess.run(tf_ssum3))

tf.sparse_segment_sum
[[0 0 0 0]]
[[ 1  2  3  4]
 [-1 -2 -3 -4]]
[[0 0 0 0]
 [5 6 7 8]]


---

In [88]:
##########################
# tf.sparse_segment_mean
##########################
c = tf.constant ([[ 1. , 2. , 3. , 4. ], [- 1. , - 2. , - 3. , - 4. ], [ 5. , 6. , 7. , 8. ]])
tf_smean1 = tf.sparse_segment_mean (c, tf.constant([ 0 , 1 ]), tf.constant([ 0 , 0 ]))
tf_smean2 = tf.sparse_segment_mean (c, tf.constant([ 0 , 1 ]), tf.constant([ 0 , 1 ]))
tf_smean3 = tf.sparse_segment_mean (c, tf.constant([ 0 , 1 , 2 ]), tf.constant([ 0 , 0 , 1 ]))

print("tf.sparse_segment_mean")
with	tf.Session()	as	sess:  
  print(sess.run(tf_smean1))
  print(sess.run(tf_smean2))
  print(sess.run(tf_smean3))

tf.sparse_segment_mean
[[0. 0. 0. 0.]]
[[ 1.  2.  3.  4.]
 [-1. -2. -3. -4.]]
[[0. 0. 0. 0.]
 [5. 6. 7. 8.]]
