# Lista de exercícios sobre libraria Numpy

<br/>**Disciplina**: Introdução a redes neurais profundas 2018/2
<br/>**Professor**: Jorge Leonid Aching Samatelo

**Aluno**: Pedro Farias

## Tabela de conteúdos
1. [Indicações](#indicacoes)
1. [Exercícios sobre Numpy](#ExerNumpy)
1. [Exercícios de Programação](#ExerProgramacao)
1. [Exercícios de Vetorização](#ExerVetor)

## Indicações <a name="indicacoes"></a>

### Considerações
* Cada aluno enviará por e-mail a solução dos exercícios propostos, tais soluções devem ser inseridas neste mesmo arquivo. 
* Para saber sobre a libraria `numpy` é necessario ler os slides `NUMPY_2x2.pdf`.
* Para saber cómo trabalhar com arquivos `*.ipynb` é necessario ler os slides `003_JUPYTER_2x2.pdf`.
* Usar o interprete de `python 3.5`.

### Prazo
* Envio das soluções: 30/08/2018 - (23:59 hrs) 

### Procedimento para o envio das soluções
* O arquivo `*.ipynb` com as soluções dos exercícios deve ser enviado ao email <jlasam001@gmail.com> com o assunto: `LISTA_EXERCICIO_NUMPY_2018_2`. 
* O nome do arquivo `*.ipynb` deve iniciar com o rotulo `DL_LISTA_NUMPY` seguido pelas iniciais do nome do aluno que soluciono os exercícios (por exemplo, o aluno Pedro Farias enviara o arquivo `DL_LISTA_NUMPY_PF.ipynb`).

### Dicas execução
* Carregue todos os pacotes que serão necessários no início do arquivo.
* Para executar comandos da shell dentro do notebook, utilize o prefixo `!` antes do comando de shell. (e.g. para listar os arquivos da pasta atual faça `! ls` para UNIX ou `! dir` para Windows.

## Exercícios sobre Numpy <a name="ExerString"></a>

### Exe. 1
Crie uma matriz nxn com valores 1,2,...,n-1 logo abaixo da diagonal.

Exemplo: Considerando n = 4.
```
A = [0 0 0 0 0]
    [1 0 0 0 0]
    [0 2 0 0 0]
    [0 0 3 0 0]
    [0 0 0 4 0]
```

In [0]:
#inserir tua solução aqui

### Exe. 2
Crie uma matriz nxn com 1 na borda e 0 dentro.

Exemplo: Considerando n = 10.
```
Z = [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
    [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
```

In [0]:
#inserir tua solução aqui

### Exe. 3
Crie uma matriz nxn, com n par, e preenchê-lo com um padrão de xadrez.

Exemplo: Considerando n = 8.
```
Z = [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
    [0 1 0 1 0 1 0 1]
    [1 0 1 0 1 0 1 0]
```

In [0]:
#inserir tua solução aqui

### Exe. 4
Criar um vetor de tamanho 10 inicializada com valores entre $<0,1>$.

Exemplo:
```
Z= [0.091 0.181 0.272 0.363 0.454 0.545 0.636 0.727 0.818 0.909]
```

In [0]:
#inserir tua solução aqui

### Exe. 5
Dado um array, negar todos os elementos que estão entre 3 e 8.

Exemplo:
```
Zorg =  [ 0  1  2  3  4  5  6  7  8  9 10]
Ztrf =  [ 0  1  2  3 -4 -5 -6 -7 -8  9 10]
```

In [0]:
#inserir tua solução aqui

### Exe. 6
Extraia a parte inteira de uma array de números aleatórios entre  1.0 e 10.0 usando 5 métodos diferentes.

Exemplo (para um caso):
```
Z  =  [7.497 6.573 9.946 2.645 2.501 8.911 4.301 9.643 4.361 4.128]
Z1 =  [ 7.  6.  9.  2.  2.  8.  4.  9.  4.  4.]
```

In [0]:
#inserir tua solução aqui

### Exe. 7
Considere dois arrays $A$ e $B$ aleatórios inicializados com valores aleatorios inteiros, verifique se eles são iguais.

Exemplo:
```
A =  [2 2 0 2 1]
B =  [1 0 2 3 3]
False
```

In [0]:
#inserir tua solução aqui

### Exe. 8
Considere uma matriz aleatória de 10x2 que representa coordenadas cartesianas, converta-as em coordenadas polares.

In [0]:
#inserir tua solução aqui

### Exe. 9
Considere o vetor [1, 2, 3, 4, 5], como construir um novo vetor com 3 zeros consecutivos intercalados entre cada valor.

Exemplo:
```
Zorg =  [1 2 3 4 5]
Z000 =  [ 1.  0.  0.  0.  2.  0.  0.  0.  3.  0.  0.  0.  4.  0.  0.  0.  5.]
```

In [0]:
#inserir tua solução aqui

### Exe. 10
Encontre o valor mais próximo de um dado valor em um array.

Exemplo:
```
Z =  [0.198 0.825 0.057 0.695 0.0333 0.793 0.526 0.547 0.787  0.656]
valor =  0.5
valor proximo em Z = 0.526929001754
```

In [0]:
#inserir tua solução aqui

## Exercícios de Programação <a name="ExerProgramacao"></a>

### Exe. 1

Como encontrar o valor mais freqüente em um array?

Exemplo:
```
Z = [8 1 8 1 9 6 2 7 0 1 7 1 6 7 9 6 0 2 1 9 8 9 0 6 9 7 1 4 2 8 1 6 4 6 1 3 5 0 1 1 5 5 0 9 4 9 9 1 1 2]
ValMoreFreq = 1
```

In [0]:
#inserir tua solução aqui

### Exe. 2

Considere duas matrizes A e B de forma (8,3) e (2,2). Como encontrar as linhas de A que contêm elementos de cada linha de B independentemente da ordem dos elementos em B? 

Exemplo:
```
A = [[2 1 4]
     [3 2 2]
     [3 4 1]
     [3 0 0]
     [4 3 4]
     [0 0 1]
     [2 1 4]
     [0 3 1]]
B = [[1 4]
     [2 4]]
rows = [0 1 2 4 6]
```

In [0]:
#inserir tua solução aqui

### Exe. 3
Dado um array bidimensional, como extrair linhas unicas?

Exemplo:
```
Z = [[0 0 1]
     [1 0 0]
     [1 1 0]
     [1 1 1]
     [0 1 1]
     [1 1 0]]
Zu = [[0 0 1]
      [0 1 1]
      [1 0 0]
      [1 1 0]
      [1 1 1]]
```

In [0]:
#inserir tua solução aqui

### Exe. 4
Converter um vetor de inteiros em uma matriz que seja sua representação binária.

Exemplo:
```
I = [0 1 2 3 15 16 32 64 128]
B = [[0 0 0 0 0 0 0 0]
     [0 0 0 0 0 0 0 1]
     [0 0 0 0 0 0 1 0]
     [0 0 0 0 0 0 1 1]
     [0 0 0 0 1 1 1 1]
     [0 0 0 1 0 0 0 0]
     [0 0 1 0 0 0 0 0]
     [0 1 0 0 0 0 0 0]
     [1 0 0 0 0 0 0 0]]
```

In [0]:
#inserir tua solução aqui

### Exe. 5
Considerando uma matriz 10x3, extraia linhas com valores desiguais (por exemplo, [2,2,3])

Exemplo:
```
Z = [[2 2 0]
     [1 1 3]
     [4 3 3]
     [1 0 1]
     [2 2 2]
     [2 3 3]
     [1 1 0]
     [0 2 0]
     [4 4 0]
     [4 2 3]]
Zd = [[2 2 0]
      [1 1 3]
      [4 3 3]
      [1 0 1]
      [2 3 3]
      [1 1 0]
      [0 2 0]
      [4 4 0]
      [4 2 3]]
```

In [0]:
#inserir tua solução aqui

## Exercícios de Vetorização <a name="ExerVetor"></a>

### Exe. 1
Sejam $𝐴$ e $𝐵$ matrizes de tamanho $10 \times 100$, calcule a **distância cosseno** entre suas as respectivas linhas. 
 * Não deve ser usado nenhum tipo de laço iterativo nem a biblioteca do `scikitlearn`. 
 * Tudo deve ser feito de forma matricial. 
 
A **distância cosseno** entre as linhas $i$-ésimas das matrizes $𝐴$ e $𝐵$ é dada pela expressção:
$$
𝑑_{c}=1 − 𝑐𝑜𝑠(a_{𝑖,:},b_{𝑖,:})
$$

Exemplo:
```
A = np.ones((10,100))  
B = np.reshape(np.arange(10*100),(10,100))
dist_cos = [0.13615328 0.0181352  0.0066263  0.00339341 0.00205563 0.00137693
 0.00098615 0.00074083 0.00057682 0.0004618 ]

```

In [0]:
#inserir tua solução aqui